safe: false
lsi: false
highlighter: rouge
markdown: kramdown
url: https://mm0hai.net
author: River MacLeod
email: web@mm0hai.net
include: [".well-known"]

defaults:
 - scope:
     path: "" # an empty string here means all files in the project
   values:
     lang: "en"
